@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'cho il hwan test cds view'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define root view entity yIH_TEST01  provider contract transactional_query as projection on  I_SalesOrderTP as SalesOrderTP
{
    key SalesOrder,
    SalesOrderType,
    SoldToParty,
    SalesOrganization,
    DistributionChannel,
    ReferenceDistributionChannel,
    OrganizationDivision,
    SalesOffice,
    SalesGroup,
    SalesDistrict,
    PurchaseOrderByCustomer,
    CustomerPurchaseOrderType,
    CustomerPurchaseOrderDate,
    PurchaseOrderByShipToParty,
    CustomerGroup,
    AdditionalCustomerGroup1,
    AdditionalCustomerGroup2,
    AdditionalCustomerGroup3,
    AdditionalCustomerGroup4,
    AdditionalCustomerGroup5,
    SDDocumentReason,
    PricingDate,
    ServicesRenderedDate,
    BillingDocumentDate,
    SDPricingProcedure,
    CustomerPriceGroup,
    PriceListType,
    RequestedDeliveryDate,
    DeliveryDateTypeRule,
    ShippingCondition,
    CompleteDeliveryIsDefined,
    OrderCombinationIsAllowed,
    SlsDocIsRlvtForProofOfDeliv,
    ShippingType,
    ReceivingPoint,
    IncotermsClassification,
    IncotermsVersion,
    IncotermsLocation1,
    IncotermsLocation2,
    FixedValueDate,
    TaxDepartureCountry,
    VATRegistrationCountry,
    HeaderBillingBlockReason,
    DeliveryBlockReason,
    SalesOrderApprovalReason,
    CustomerPaymentTerms,
    BillingCompanyCode,
    PaymentMethod,
    CustomerAccountAssignmentGroup,
    TransactionCurrency,
    AssignmentReference,
    AccountingDocExternalReference,
    @Semantics.amount.currencyCode: 'TransactionCurrency'
    TotalNetAmount,
    ReferenceSDDocument,
    CustomerCreditAccount,
    OverallSDProcessStatus,
    OverallDeliveryBlockStatus,
    OverallBillingBlockStatus,
    OverallDeliveryStatus,
    TotalCreditCheckStatus,
    OverallSDDocumentRejectionSts,
    TotalBlockStatus,
    HdrGeneralIncompletionStatus,
    OvrlItmGeneralIncompletionSts,
    OverallSDDocReferenceStatus,
    SalesDocApprovalStatus,
    OverallChmlCmplncStatus,
    OverallDangerousGoodsStatus,
    OverallSafetyDataSheetStatus,
    OverallTrdCmplncEmbargoSts,
    OvrlTrdCmplncSnctndListChkSts,
    OvrlTrdCmplncLegalCtrlChkSts,
    SalesOrderDownPaymentStatus,
    OverallOrdReltdBillgStatus,
    BusinessSolutionOrder,
    LastChangeDateTime,
    SalesOrderDate,
    SalesOrderProcessingType,
    ControllingArea,
    CreatedByUser,
    CreationDate,
    CreationTime,
    SalesDocumentCreationDateTime,
    LastChangedByUser,
    LastChangeDate,
    IsEUTriangularDeal,
    ReferenceSDDocumentCategory,
    /* Associations */
    _Item,
    _Partner,
    _PricingElement,
    _Text
}
