@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'i_purchase order wrapper cds view'
@Metadata.ignorePropagatedAnnotations: true
define root view entity Y_R_PURCHASEORDER as select from I_PurchaseOrderAPI01
association to I_SupplierPurchasingOrg as _SupplierPurchasingOrg on $projection.Supplier = _SupplierPurchasingOrg.Supplier and
                                                                    $projection.PurchasingOrganization = _SupplierPurchasingOrg.PurchasingOrganization  
{
    key PurchaseOrder,
    PurchaseOrderType,
    PurchaseOrderSubtype,
    PurchasingDocumentOrigin,
    CreatedByUser,
    CreationDate,
    PurchaseOrderDate,
    Language,
    CorrespncExternalReference,
    CorrespncInternalReference,
    PurchasingDocumentDeletionCode,
    ReleaseIsNotCompleted,
    PurchasingCompletenessStatus,
    PurchasingProcessingStatus,
    PurgReleaseSequenceStatus,
    ReleaseCode,
    CompanyCode,
    PurchasingOrganization,
    PurchasingGroup,
    Supplier,
    ManualSupplierAddressID,
    SupplierRespSalesPersonName,
    SupplierPhoneNumber,
    SupplyingSupplier,
    SupplyingPlant,
    InvoicingParty,
    Customer,
    SupplierQuotationExternalID,
    PaymentTerms,
    CashDiscount1Days,
    CashDiscount2Days,
    NetPaymentDays,
    CashDiscount1Percent,
    CashDiscount2Percent,
    DownPaymentType,
    DownPaymentPercentageOfTotAmt,
     @Semantics.amount.currencyCode: 'DocumentCurrency'
    DownPaymentAmount,
    DownPaymentDueDate,
    IncotermsClassification,
    IncotermsTransferLocation,
    IncotermsVersion,
    IncotermsLocation1,
    IncotermsLocation2,
    IsIntrastatReportingRelevant,
    IsIntrastatReportingExcluded,
    PricingDocument,
    PricingProcedure,
    DocumentCurrency,
    ValidityStartDate,
    ValidityEndDate,
    ExchangeRate,
    ExchangeRateIsFixed,
    LastChangeDateTime,
    TaxReturnCountry,
    VATRegistration,
    VATRegistrationCountry,
    PurgReasonForDocCancellation,
    @Semantics.amount.currencyCode: 'DocumentCurrency'
    PurgReleaseTimeTotalAmount,
    PurgAggrgdProdCmplncSuplrSts,
    PurgAggrgdProdMarketabilitySts,
    PurgAggrgdSftyDataSheetStatus,
    PurgProdCmplncTotDngrsGoodsSts,
    /* Associations */
    _PurchaseOrderItem,
    _PurchasingGroup,
    _Supplier,
    _SupplierPurchasingOrg //MM-0024 선금 정보 업데이트 2025.07.31
}
