CLASS zbp_i_online_shop_007 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZI_online_SHOP_007.
 PUBLIC SECTION.
 class-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED i_purchaserequisitiontp.
ENDCLASS.



CLASS ZBP_I_ONLINE_SHOP_007 IMPLEMENTATION.
ENDCLASS.
