@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: '[MM] productplant test'
@Metadata.ignorePropagatedAnnotations: true
define root view entity z_mm_test01 as select from I_ProductPlantBasic
{
 
    key Product,
    key Plant,
//    PurchasingGroup,
//    CountryOfOrigin,
//    RegionOfOrigin,
//    ProductionInvtryManagedLoc,
//    ProfileCode,
//    ProfileValidityStartDate,
//    AvailabilityCheckType,
//    FiscalYearVariant,
//    PeriodType,
//    ProfitCenter,
//    GoodsReceiptDuration,
//    MaintenanceStatusName,
//    IsMarkedForDeletion,
//    MRPType,
//    MRPResponsible,
//    ABCIndicator,
//    MinimumLotSizeQuantity,
//    MaximumLotSizeQuantity,
//    FixedLotSizeQuantity,
//    ConsumptionTaxCtrlCode,
//    IsCoProduct,
//    ConfigurableProduct,
//    StockDeterminationGroup,
//    HasPostToInspectionStock,
//    IsBatchManagementRequired,
//    SerialNumberProfile,
//    IsNegativeStockAllowed,
//    HasConsignmentCtrl,
//    IsPurgAcrossPurgGroup,
//    IsInternalBatchManaged,
//    ProductCFOPCategory,
//    ProductIsExciseTaxRelevant,
//    UnderDelivToleranceLimit,
//    OverDelivToleranceLimit,
//    ProcurementType,
//    SpecialProcurementType,
//    ProductionSchedulingProfile,
//    ProductionSupervisor,
//    SafetyStockQuantity,
//    GoodsIssueUnit,
//    SourceOfSupplyCategory,
//    ConsumptionReferenceProduct,
//    ConsumptionReferencePlant,
//    ConsumptionRefUsageEndDate,
//    ConsumptionQtyMultiplier,
//    ProductUnitGroup,
//    DistrCntrDistributionProfile,
//    ConsignmentControl,
//    GoodIssueProcessingDays,
//    PlannedDeliveryDurationInDays,
//    ProductIsCriticalPrt,
//    ProductLogisticsHandlingGroup,
//    MaterialFreightGroup,
//    OriginalBatchReferenceMaterial,
//    OriglBatchManagementIsRequired,
//    ProductConfiguration,
//    ProductMinControlTemperature,
//    ProductMaxControlTemperature,
//    ProductControlTemperatureUnit,
//    ValuationCategory,
//    BaseUnit,
//    ItemUniqueIdentifierIsRelevant,
//    ItemUniqueIdentifierType,
//    ExtAllocOfItmUnqIdtIsRelevant,
    YY1_TransferDate_PLT,
    YY1_TransferStatus_PLT,
    _Product.CreatedByUser,
    _Product.CreationDateTime,
    _Product.LastChangeDateTime,
    _Product.LastChangedByUser,
    /* Associations */
//    _ABCIndicator,
//    _ABCIndicatorDesc,
//    _CFOPDesc,
//    _ConfigurableProduct,
//    _ConfigurableProductName,
//    _CountryOfOriginText,
//    _DistributionProfile,
//    _DistributionProfileText,
//    _FiscalYearVariant,
//    _FiscalYearVariantDescription,
//    _GoodsIssueUnit,
    _GoodsMovementQuantity,
    _MaterialLotSizingProcedure,
    _MaterialStock,
//    _MRPController,
//    _MRPType,
//    _PeriodType,
//    _PeriodTypeText,
    _Plant,
    _PlantESPP,
    _PlantProcurement,
    _PlantQualityMgmt,
    _PlantSales,
//    _ProdControlTemperatureUnit,
//    _ProdCtrlTemperatureUnitText,
    _ProdPlantInternationalTrade,
    _Product,
//    _ProductCFOPCategory,
//    _ProductFreightGroup,
//    _ProductFreightGroupText,
    _ProductPlantCosting,
    _ProductPlantForecast,
//    _ProductStatus,
//    _ProductStatusText,
    _ProductStorageLocation,
//    _PurchasingGroup,
//    _RegionText,
    _Site,
//    _SourceOfSupplyCategory,
    _Stock,
//    _StockDeterminationGroup,
//    _StockDeterminationGroupT,
    _Text
//    _UnitOfMeasureText
}
